# config.yaml  (repo root)

# ── global defaults ────────────────────────────────────────────────
EMBEDDING_MODEL: all-MiniLM-L6-v2
MAX_FILE_SIZE: 102400          # bytes
WORKERS: 8
SKIP_DIRS:
  - .git               # VCS history
  - __pycache__        # Python bytecode
  - .venv              # Virtual‐envs
  - venv               # alternative virtual‐env name
  - node_modules       # JS deps
  - build              # build outputs
  - dist               # distribution packages
  - target             # Maven/Gradle Java outputs
  - bazel-bin          # Bazel build artifacts
  - bazel-out          # Bazel intermediate files
  - third_party        # Vendored code (often huge)
  - vendor             # Go/Rust vendored deps
  - .pytest_cache      # Pytest cache
  - .mypy_cache        # Mypy cache
  - .idea              # IDE project files (IntelliJ)
  - .vscode            # VSCode settings
  - coverage           # coverage reports
  - logs               # runtime logs
  - tmp                # temp files
MIN_THRESHOLD: 0
# Maximum number of lines before we switch to coarse chunking
MAX_LINES_COARSE: 5000
MAX_TS_CHUNK_CONTENT: 100000
# AST-based chunker settings:
# Max number of AST top-level nodes to emit as separate chunks;
# if exceeded, you can group into larger “coarse” chunks.
MAX_AST_CHUNK_NODES: 50
# Alternatively, limit by total lines per AST chunk
MAX_AST_CHUNK_LINES: 500
# ── reflective agent settings ──────────────────────────────────────
reflective:
  plan_refinement:
    max_reasoning_steps: 3
    scope:
      max_tokens:   5000
      max_cost:     0.50
      auto_approve: 0.05
  issue_resolution:
    max_reasoning_steps: 2
    scope:
      max_tokens:   3000
      max_cost:     0.30
  validation:
    strict_schema: true
    allow_large_patch: false
